FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir pmdarima fastapi uvicorn[standard]

COPY pmdarima_service.py .

CMD ["uvicorn", "pmdarima_service:app", "--host", "0.0.0.0", "--port", "8081"]
