version: "3.8"

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile  # your Python 3.11 Dockerfile
    container_name: main_app
    ports:
      - "5000:5000"
    depends_on:
      - arima-sidecar
    environment:
      - ARIMA_SIDECAR_URL=http://arima-sidecar:8000
    networks:
      - trading_net

  arima-sidecar:
    build:
      context: .
      dockerfile: Dockerfile.arima
    container_name: arima_sidecar
    ports:
      - "8000:8000"
    networks:
      - trading_net

networks:
  trading_net:
    driver: bridge
